# Generated by Django 6.0.3 on 2026-03-26 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutbook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='image',
        ),
    ]
